FROM node:20-alpine

RUN apk add --no-cache libc6-compat
RUN npm install -g turbo

WORKDIR /app

EXPOSE 3000 3001 5555

COPY docker-entrypoint.sh ./
RUN sed -i 's/\r$//' ./docker-entrypoint.sh && chmod +x ./docker-entrypoint.sh

ENTRYPOINT ["/bin/sh", "./docker-entrypoint.sh"]
